env:
  TERM: xterm-256color

# Fonts
font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 14

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
  - { key: Slash, mods: Control, chars: "\x1f" }

schemes:
  # https://github.com/sonph/onehalf
  onehalf: &onehalf
    primary:
      background: '#282c34'
      foreground: '#dcdfe4'

    normal:
      black: '#282c34'
      red: '#e06c75'
      green: '#98c379'
      yellow: '#e5c07b'
      blue: '#61afef'
      magenta: '#c678dd'
      cyan: '#56b6c2'
      white: '#dcdfe4'

    bright:
      black: '#282c34'
      red: '#e06c75'
      green: '#98c379'
      yellow: '#e5c07b'
      blue: '#61afef'
      magenta: '#c678dd'
      cyan: '#56b6c2'
      white: '#dcdfe4'

  # https://github.com/folke/tokyonight.nvim
  tokyo-night: &tokyo-night
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'

    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#787c99'

    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

colors: *onehalf
