env:
  TERM: xterm-256color

# Fonts
font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  #size: 16

# Colors (One Half Dark)
colors:
  primary:
    background: '#282c34'
    foreground: '#dcdfe4'

  normal:
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#e5c07b'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#dcdfe4'

  bright:
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#e5c07b'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#dcdfe4'

background_opacity: 1.0

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
  - { key: Slash, mods: Control, chars: "\x1f" }
