env:
  TERM: xterm-256color

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"
  
# Colors (One Half Dark)
colors:
  primary:
    background: '0x282c34'
    foreground: '0xdcdfe4'

  normal:
    black: '0x282c34'
    red: '0xe06c75'
    green: '0x98c379'
    yellow: '0xe5c07b'
    blue: '0x61afef'
    magenta: '0xc678dd'
    cyan: '0x56b6c2'
    white: '0xdcdfe4'

  bright:
    black: '0x282c34'
    red: '0xe06c75'
    green: '0x98c379'
    yellow: '0xe5c07b'
    blue: '0x61afef'
    magenta: '0xc678dd'
    cyan: '0x56b6c2'
    white: '0xdcdfe4'

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
