# Colors (One Half Dark)
# Source: https://github.com/sonph/onehalf

[colors.bright]
black = '#282c34'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#dcdfe4'

[colors.normal]
black = '#282c34'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#dcdfe4'

[colors.primary]
background = '#282c34'
foreground = '#dcdfe4'
