#!/usr/bin/env zsh

# MARK: Requirements:
# 1. Setup ssh config with github. doc: https://docs.gitlab.com/ee/user/ssh.html

# MARK: Pre-setup
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# MARK: Main:
# Install homebrew - requires password
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install homebrew stuff
brew bundle

# MARK: - Zsh
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# MARK: - Neovim
# install vim-plug: https://github.com/junegunn/vim-plug
nvim --headless +PlugInstall +qa

luarocks install luacheck
noglob pip3 install python-lsp-server[all]

# MARK: - LLDB
git clone git@github.com:DerekSelander/LLDB.git ~/lldb/LLDB
git clone git@github.com:facebook/chisel.git ~/lldb/chisel
