colors:
  body: none
  date: yellow
  tags: magenta
  title: none
default_hour: 9
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default:
    encrypt: false
    journal: $HOME/.local/share/jrnl/journal.txt
linewrap: 79
tagsymbols: '#@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v4.2.1
