# config: https://starship.rs/config/

[[battery.display]]
threshold = 20
style = "bold red"

[git_branch]
symbol = "🌱 "

[status]
style = "bg:blue"
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[swift]
symbol = " "
