
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew bazelisk
brew brotli
brew c-ares
brew carthage
brew cmake
brew gdbm
brew gettext
brew git
brew git-lfs
brew grpcurl
brew highlight
brew icu4c
brew jemalloc
brew jq
brew libev
brew libevent
brew libtermkey
brew libuv
brew libvterm
brew lua
brew luajit --HEAD
brew luajit-openresty
brew luarocks
brew luv
brew m4
brew mas
brew mint
brew mpdecimal
brew msgpack
brew ncurses
brew neovim
brew nghttp2
brew node
brew oniguruma
brew openjdk
brew openjdk@11
brew openssl@1.1
brew pcre2
brew pkg-config
brew protobuf
brew pyenv
brew python@3.9
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew sdl2
brew six
brew sourcekitten
brew sqlite
brew swift-protobuf
brew swiftlint
brew telnet
brew terminal-notifier
brew tig
brew tmux
brew tokei
brew tree
brew tree-sitter
brew unibilium
brew utf8proc
brew vapor
brew vifm
brew xcbeautify
brew xclogparser
brew xz

tap homebrew/cask
cask alacritty

tap bradleyjkemp/formulae

tap peripheryapp/periphery
cask periphery

tap rappinc/rappi-army-knife

tap rappinc/tap

tap rcmdnk/file
brew brew-file

tap vapor/tap

# App Store applications
appstore 1333542190  1Password 7  (7.8.6)
appstore 1091189122  Bear         (1.8.4)
appstore 682658836   GarageBand   (10.4.3)
appstore 408981434   iMovie       (10.2.4)
appstore 1035137927  KeyKey       (2.9)
appstore 409183694   Keynote      (11.1)
appstore 405399194   Kindle       (1.31.0)
appstore 1116599239  NordVPN IKE  (6.5.0)
appstore 409203825   Numbers      (11.1)
appstore 409201541   Pages        (11.1)
appstore 1504940162  RocketSim    (4.1.2)
appstore 803453959   Slack        (4.17.0)
appstore 1176895641  Spark        (2.9.23)
appstore 904280696   Things       (3.13.13)
appstore 1147396723  WhatsApp     (2.2121.7)
appstore 497799835   Xcode        (12.5.1)
