# source: https://github.com/Homebrew/homebrew-bundle

# MARK: Taps

tap "keith/formulae"
tap "xcodesorg/made"

# MARK: Formulas

brew "aria2"
brew "bat"
brew "bazelisk"
brew "bloaty"
brew "buildifier"
brew "cowsay"
brew "direnv"
brew "duf"
brew "dust"
brew "eza"
brew "fd"
brew "fortune"
# NOTE: run `$(brew --prefix)/opt/fzf/install`  in terminal after installation
brew "fzf"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "glow"
brew "graphviz"
brew "highlight"
brew "htop"
brew "httpie"
brew "ideviceinstaller"
brew "jq"
brew "jrnl"
brew "keith/formulae/zsh-xcode-completions"
brew "mas"
brew "mgba"
brew "neofetch"
brew "node"
brew "ripgrep"
brew "ruby@3.1"
brew "sqlite"
brew "starship"
brew "swiftformat"
brew "swiftgen"
brew "swiftlint"
brew "telnet"
brew "tig"
brew "tldr"
brew "tmux"
brew "tokei"
brew "vifm"
brew "wget"
brew "xcodesorg/made/xcodes"
brew "yamllint"

# MARK: Neovim

#brew "neovim", args: ["HEAD"]
brew "neovim"

brew "cpplint"
brew "shellcheck"
brew "lua-language-server"
brew "tree-sitter"

# MARK: Fonts

cask "font-hack-nerd-font"

# MARK: Applications

cask "alacritty"
cask "alfred"
cask "bartender"
cask "batteries"
cask "daisydisk"
cask "firefox"
cask "google-drive"
cask "openemu"
cask "proxyman"
cask "rectangle"
cask "sensei"
cask "slack"
cask "via"
cask "whatsapp"
cask "1password"

mas "Bear", id: 1091189122
mas "Kindle", id: 405399194
mas "RocketSim", id: 1504940162
mas "Spark", id: 1176895641
mas "Things", id: 904280696
mas "1Password for Safari", id: 1569813296
mas "Timer RH", id: 929960914
